# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.2
language: objective-c
xcode_workspace: Example/SlidingNumberView.xcworkspace #3
xcode_scheme: SlidingNumberView-Example #4
xcode_sdk: iphonesimulator9.3
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
# script:


# - xcodebuild clean test -enableCodeCoverage YES -scheme SlidingNumberView-Example -destination "platform=iOS Simulator,name=iPhone 6,OS=12" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet | xcpretty
# - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SlidingNumberView.xcworkspace -scheme SlidingNumberView-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint
